### ISSUE TITLE
duplicate key error for user 

### ISSUE THREAD

**Issue by martinn8145** [atran25/carservation.server#15]
Getting the following error when sending reservation post request:

E11000 duplicate key error collection: myFirstDatabase.users index: userId_1 dup key: { userId: null }
MongoServerError: E11000 duplicate key error collection: myFirstDatabase.users index: userId_1 dup key: { userId: null }
    at /Users/martinnguyen/Documents/cs160proj/backend/carservation.server/node_modules/mongodb/lib/operations/insert.js:51:33
    at /Users/martinnguyen/Documents/cs160proj/backend/carservation.server/node_modules/mongodb/lib/cmap/connection_pool.js:273:25
    at handleOperationResult (/Users/martinnguyen/Documents/cs160proj/backend/carservation.server/node_modules/mongodb/lib/sdam/server.js:363:9)
    at MessageStream.messageHandler (/Users/martinnguyen/Documents/cs160proj/backend/carservation.server/node_modules/mongodb/lib/cmap/connection.js:474:9)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (/Users/martinnguyen/Documents/cs160proj/backend/carservation.server/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
    at MessageStream._write (/Users/martinnguyen/Documents/cs160proj/backend/carservation.server/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)

**Comment by martinn8145** [comment]
not getting error anymore
